#!/bin/bash


echo "

class passwd {
file { '/etc/passwd':
owner => root,
group => root,
mode => 644,
}
}


class wall {
exec { 'wall':
command => '/usr/bin/wall IT WORKS'
}
}

node default { }
node 'ubuntu' {
include wall
}

node 'centos' {
include wall
}
#this part is about installation of packages with apache2 as example

#ubuntu example
class apache {
resource { 'apt-update':
command => '/usr/bin/apt-get update'
}

package { 'apache2':
require => resource,
ensure => installed,
}

service { 'apache2':
require => resource,
ensure => running,
}
}

node default { }
node 'ubuntu' {
include apache
}

#centos example

class httpd {
resource { 'yum update':
command => '/usr/bin/yumdate'
}

package { 'httpd'
require => resource,
ensure => installed,
}

service { 'httpd'
require => resource,
ensure => running,
}
}

node default { }
node 'centos' {
include httpd
}




" > /etc/puppet/manifests/site.pp

