#!/bin/bash


echo "

class passwd {
file { '/etc/passwd':
owner => root,
group => root,
mode => 644,
}
}


class wall {
exec { 'wall':
command => '/usr/bin/wall IT WORKS'
}
}

node default { }
node 'ubuntu' {
include wall
}

node 'centos' {
include wall
}


}
" > /etc/puppet/manifests/site.pp

