#!/bin/bash

echo "
node default { }
#node 'ubuntu' {
#include wall
#}

#node 'centos' {
#include wall
#}
#this part is about installation of packages with apache2 as example

#ubuntu example
class apache {
exec { 'apt-update':
command => '/usr/bin/apt-get update'
}

package { 'apache2':
require => exec['apt-update'],
ensure => installed,
}

service { 'apache2':
require => package['apache2'],
ensure => running,
}
}

#node default { }
node 'ubuntu' {
include apache
include wall
}

#centos example

class httpd {
exec { 'yum update':
command => '/usr/bin/yum -y update'
}

package { 'httpd':
require => exec['yum update'],
ensure => installed,
}

service { 'httpd':
require => package['httpd'],
ensure => running,
}
}

#node default { }
node 'centos' {
include httpd
include wall
}



" > /etc/puppet/manifests/site.pp

